import type { SiteConfig } from "~/types";

const config: SiteConfig = {
  site: "https://sanyuesha.com",
  title: "三月沙 · 前端与产品思考",
  description: "前沿资讯、技术实践、作品与工具分享，Markdown/MDX 驱动的个人站点。",
  author: "三月沙",
  tags: ["Frontend", "Product", "Sanyuesha"],
  socialCardAvatarImage: "./src/content/avatar.jpg",
  font: "JetBrains Mono Variable",
  pageSize: 6,
  trailingSlashes: false,
  navLinks: [
    { name: "Home", url: "/" },
    { name: "Blog", url: "/posts" },
    { name: "Insights", url: "/insights" },
    { name: "Projects", url: "/projects" },
    { name: "Tools", url: "/tools" },
    { name: "Timeline", url: "/timeline" }
  ],
  themes: {
    mode: "select",
    default: "catppuccin-mocha",
    include: [
      "andromeeda",
      "aurora-x",
      "ayu-dark",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
      "dark-plus",
      "dracula",
      "dracula-soft",
      "everforest-dark",
      "everforest-light",
      "github-dark",
      "github-dark-default",
      "github-dark-dimmed",
      "github-dark-high-contrast",
      "github-light",
      "github-light-default",
      "github-light-high-contrast",
      "gruvbox-dark-hard",
      "gruvbox-dark-medium",
      "gruvbox-dark-soft",
      "gruvbox-light-hard",
      "gruvbox-light-medium",
      "gruvbox-light-soft",
      "houston",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
      "laserwave",
      "light-plus",
      "material-theme",
      "material-theme-darker",
      "material-theme-lighter",
      "material-theme-ocean",
      "material-theme-palenight",
      "min-dark",
      "min-light",
      "monokai",
      "night-owl",
      "nord",
      "one-dark-pro",
      "one-light",
      "plastic",
      "poimandres",
      "red",
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-moon",
      "slack-dark",
      "slack-ochin",
      "snazzy-light",
      "solarized-dark",
      "solarized-light",
      "synthwave-84",
      "tokyo-night",
      "vesper",
      "vitesse-black",
      "vitesse-dark",
      "vitesse-light"
    ],
    overrides: {}
  },
  socialLinks: {
    github: "https://github.com/zhyq0826",
    rss: true
  },
  giscus: undefined,
  characters: {
    owl: "/owl.webp",
    unicorn: "/unicorn.webp",
    duck: "/duck.webp"
  }
};

export default config;

